# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=500)),
                ('link', models.URLField()),
                ('itch_game_name', models.CharField(max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('preview_image', models.ImageField(upload_to='games/preview_image/')),
            ],
            options={
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Category'),
        ),
    ]
