# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180321_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default='', upload_to='blog/preview_image/'),
            preserve_default=False,
        ),
    ]
