# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/preview_image/'),
        ),
    ]
