# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
