# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'genres'},
        ),
    ]
